name: Deploy on Push to Main

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          path: /temp/.build-cache
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buildx-

      - name: Login to Github container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
            
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/sangddong/pfweb-client-image:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ARN}}
          aws-region: ap-northeast-2

      - name: Verify Docker Login
        run: |
          echo ${{secrets.GHCR_TOKEN}} | sudo docker login ghcr.io -u ${{github.actor}} --password-stdin
          
      - name: Docker run
        run: |
          sudo docker stop pfweb-client-container || true
          sudo docker rm pfweb-client-container || true
          sudo docker rmi ghcr.io/sangddong/pfweb-client-image:latest || true
          sudo docker run -d -p 80:3000 \
          --name pfweb-client-container \
          --restart always \
          -e PORT=${{ secrets.PORT }} \
          ghcr.io/sangddong/pfweb-client-image:latest
