name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli openssh-client
      
          echo "$EC2_SSH_KEY" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem
      
          INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $EC2_INSTANCE_ID \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
      
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ubuntu@$INSTANCE_PUBLIC_IP 'bash -s' < /home/ubuntu/deploy.sh
