name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare SSH Key
        run: |
          echo "$EC2_SSH_KEY" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem
          # Debug: Verify key file creation
          ls -l /tmp/ec2_key.pem
          file /tmp/ec2_key.pem

      - name: Retrieve EC2 instance IP and check SSH
        run: |
          INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $EC2_INSTANCE_ID \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "Instance Public IP: $INSTANCE_PUBLIC_IP"

          if [ -z "$INSTANCE_PUBLIC_IP" ]; then
            echo "Error: Unable to retrieve EC2 instance public IP address."
            exit 1
          fi

          set -x
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ubuntu@$INSTANCE_PUBLIC_IP 'echo "SSH connection successful"'
          set +x

      - name: Deploy to EC2
        run: |
          echo "Starting deployment script transfer"
          scp -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem /home/ubuntu/deploy.sh ubuntu@$INSTANCE_PUBLIC_IP:/home/ubuntu/deploy.sh
          echo "Transfer complete, executing deployment script"
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ubuntu@$INSTANCE_PUBLIC_IP 'bash -s' < /home/ubuntu/deploy.sh
