name: Deploy on Push to Main

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          path: /temp/.build-cache
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buildx-

      - name: Login to Github container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
            
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/sangddong/my-image:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{AWS_ARN}}
          aws-region: ap-northeast-2
          


